# Assignment

Deadline: 24 novembre ore 23:59.
Solve efficiently a generic n^2-1 puzzle using path search algorithm.

Cost=  total number of actions you need to __evaluate__. An action is something that bring me to a new state. For example the number of swaps to do.

The result is the sequence of action that took you at the end. The goal is not to find a state but a sequence of actions from srtarting point to end point: we do not look for a soluzion but for a sequence of actions.

# Import and Inizialization

In [65]:
from collections import namedtuple
from random import choice
from tqdm.auto import tqdm
import numpy as np
from heapq import heappop, heappush
from typing import Tuple, Union

In [66]:
PUZZLE_DIM = 5
action = namedtuple('Action', ['pos1', 'pos2'])

In [67]:
def available_actions(state: np.ndarray) -> list['Action']:
    x, y = [int(_[0]) for _ in np.where(state == 0)]
    actions = list()
    if x > 0:
        actions.append(action((x, y), (x - 1, y)))
    if x < PUZZLE_DIM - 1:
        actions.append(action((x, y), (x + 1, y)))
    if y > 0:
        actions.append(action((x, y), (x, y - 1)))
    if y < PUZZLE_DIM - 1:
        actions.append(action((x, y), (x, y + 1)))
    return actions



def do_action(state: np.ndarray, action: 'Action') -> np.ndarray:
    new_state = state.copy()
    new_state[action.pos1], new_state[action.pos2] = new_state[action.pos2], new_state[action.pos1]
    return new_state

Function to evaluate the quality of a solution (list of actions) as the total number of actions needed.

In [68]:
def qualily(actions):
    return len(actions)

The state is a numpy array.

We created a function that returns the number of actions from a state pos1 to a state pos2.

Compute 100_000 random actions:

In [69]:
RANDOMIZE_STEPS = 100_000
state = np.array([i for i in range(1, PUZZLE_DIM**2)] + [0]).reshape((PUZZLE_DIM, PUZZLE_DIM))
for r in tqdm(range(RANDOMIZE_STEPS), desc='Randomizing'):
    state = do_action(state, choice(available_actions(state)))
state

Randomizing: 100%|██████████| 100000/100000 [00:00<00:00, 116211.07it/s]


array([[14,  8,  9,  1, 18],
       [22,  0, 15,  5, 17],
       [ 2, 11, 21, 16,  4],
       [19, 12, 13,  6, 24],
       [20,  3,  7, 23, 10]])

Define a function that indicates if we end the search.

In [70]:
def test_goal(solution):
    arr_solution = np.reshape(solution, PUZZLE_DIM*PUZZLE_DIM)
    arr_solution_no_zero = arr_solution[0: len(arr_solution)-1]
    if np.all(arr_solution_no_zero[:-1] <= arr_solution_no_zero[1:]) and arr_solution[len(arr_solution)-1]==0:
        return True
    return False

# Depth search

Let's use a function that computes a value for each matrix so that it will be easy to store matrices.

This function shouuld be bi-directional: a number is associated to only one matrix and viceversa.

In [71]:
def matrix_score(matrix):
    """
    Performs the product for each element with the position in the matrix.
    
    Parameters:
    - state (np.ndarray): A state of the puzzle.
    
    Returns:
    - Score of the matrix
    """
    #flatter the matrix:
    matrice = matrix.flatten()
    score = 0
    for i in range(len(matrice)):
        score += (10**i)*matrice[i]
    return int(score)


def simplified_matrix_score(matrix):
    """
    Performs the product for each element with the position in the matrix.
    
    Parameters:
    - state (np.ndarray): A state of the puzzle.
    
    Returns:
    - Score of the matrix
    """
    #flatter the matrix:
    matrice = matrix.flatten()
    score = 0
    for i in range(len(matrice)):
        score += i*matrice[i]
    return int(score)

In [72]:
from collections import namedtuple, deque
import numpy as np

# Define action as a named tuple
action = namedtuple('Action', ['pos1', 'pos2'])

def depth_limited_search(initial_state: np.ndarray, final_state: np.ndarray, max_depth: int) -> list[action] or None:
    """
    Performs a depth-limited search to solve the n-puzzle.
    
    Parameters:
    - initial_state (np.ndarray): The starting state of the puzzle.
    - final_state (np.ndarray): The desired goal state of the puzzle.
    - max_depth (int): The maximum depth limit for the search.
    
    Returns:
    - list[action] or None: A sequence of actions leading to the solution, or None if no solution is found.
    """
    stack = deque([(initial_state, [], 0)])  # Stack of (current state, path to reach it, current depth)
    visited = set()  # Set of visited states for current path only
    optimum = matrix_score(final_state)

    while stack:
        current_state, path, depth = stack.pop()
        current_score = matrix_score(current_state)

        # Check if we reached the goal
        if current_score == optimum:
            return path
        
        # # Backtrack if depth limit reached
        # if depth >= max_depth:
        #     continue
        
        # Add current state to visited set (track only in current path)
        visited.add(current_score)
        
        # Generate and iterate over all possible moves
        for act in available_actions(current_state):
            next_state = do_action(current_state, act)
            
            # Check if the next state has already been visited in the current path
            if matrix_score(next_state) not in visited:
                # Add the new state and path to stack, increase depth
                stack.append((next_state, path + [act], depth + 1))
        
        # Remove the current state from visited set after backtracking
        #visited.remove(matrix_score(current_state))
    
    return None  # Return None if no solution is found within depth limit

# Iterative Deepening Depth-First Search (IDDFS) wrapper function
def iterative_deepening_dfs(initial_state: np.ndarray, final_state: np.ndarray, max_depth: int = 50) -> list[action] or None:
    """
    Performs an iterative deepening DFS to solve the n-puzzle.
    
    Parameters:
    - initial_state (np.ndarray): The starting state of the puzzle.
    - final_state (np.ndarray): The desired goal state of the puzzle.
    - max_depth (int): The maximum depth to limit the search for IDDFS.
    
    Returns:
    - list[action] or None: A sequence of actions leading to the solution, or None if no solution is found.
    """
    for depth in range(1, max_depth + 1):
        result = depth_limited_search(initial_state, final_state, depth)
        if result is not None:
            return result
    return None


# A*

We may also want to try to convert the numpy ndarray into a bytes object directly:

In [73]:
def state_to_bytes(state: np.ndarray) -> bytes:
    return state.tobytes()

As heuristic functions we can now try to use 3 different heuristics: 
1. manhattan distance
2. linear conflict
3. walking distance

In [74]:
class PuzzleHeuristicService:
    def __init__(self, goal_state: np.ndarray):
        self.goal_state = goal_state

    def heuristic_manhattan_distance(self, position):
        distance = 0
        size = len(position)
        for i in range(size):
            for j in range(size):
                tile = position[i][j]
                if tile != 0:
                    target_row = (tile - 1) // size
                    target_col = (tile - 1) % size
                    distance += abs(i - target_row) + abs(j - target_col)
        return distance

    def linear_conflict(self, state: np.ndarray) -> int:
        conflict = 0
        size = state.shape[0]
        for row in range(size):
            row_goal = self.goal_state[row]
            row_state = state[row]
            for i in range(size):
                for j in range(i + 1, size):
                    if (
                        row_state[i] in row_goal
                        and row_state[j] in row_goal
                        and row_state[i] > row_state[j]
                    ):
                        conflict += 2
        return conflict
    

    def heuristic_linear_conflict(self, position):
        conflict = 0
        size = len(position)

        # Row conflicts
        for row in range(size):
            max_val = -1
            for col in range(size):
                value = position[row][col]
                if value != 0 and (value - 1) // size == row:
                    if value > max_val:
                        max_val = value
                    else:
                        conflict += 2

        # Column conflicts
        for col in range(size):
            max_val = -1
            for row in range(size):
                value = position[row][col]
                if value != 0 and (value - 1) % size == col:
                    if value > max_val:
                        max_val = value
                    else:
                        conflict += 2

        return conflict

    def heuristic_walking_distance(self, position):
        # Create a grid to store the walking distances
        size = len(position)
        distance_grid = [[0] * size for _ in range(size)]

        for row in range(size):
            for col in range(size):
                value = position[row][col]
                if value != 0:
                    target_row = (value - 1) // size
                    target_col = (value - 1) % size
                    distance_grid[row][col] = abs(row - target_row) + abs(col - target_col)

        # Calculate the walking distance
        walking_distance = 0
        for row in range(size):
            for col in range(size):
                walking_distance += distance_grid[row][col]

        return walking_distance

    def combined_heuristic(self, state: np.ndarray) -> int:
        #return self.manhattan_distance(state) + self.linear_conflict(state)
        return self.heuristic_manhattan_distance(state) + self.heuristic_linear_conflict(state) + self.heuristic_walking_distance(state)



In [75]:
def enhanced_a_star(initial_state: np.ndarray, final_state: np.ndarray) -> Tuple[Union[list, None], float]:
    """
    Enhanced A* algorithm for the n-puzzle problem using modular heuristics.
    """
    heuristic_service = PuzzleHeuristicService(final_state)

    def calculate_heuristic(state: np.ndarray) -> int:
        return heuristic_service.combined_heuristic(state)

    # Priority queue: (f_score, g_score, current_state, path)
    open_set = []
    heappush(open_set, (calculate_heuristic(initial_state), 0, initial_state.tobytes(), []))
    visited = set()
    optimum = state_to_bytes(final_state)

    cost = 0

    while open_set:
        # Extract node with the lowest f score (f score= cost)
        f_score, g_score, current_bytes, path = heappop(open_set)
        current_state = np.frombuffer(current_bytes, dtype=initial_state.dtype).reshape(initial_state.shape)
        current_score = state_to_bytes(current_state)

        # Check if we finished already:
        if current_score == optimum:
            return path, float(cost) 

        # Add current node to visited
        visited.add(current_score)

        # Generate possible moves:
        for act in available_actions(current_state):
            next_state = do_action(current_state, act)
            next_score = state_to_bytes(next_state)
            if next_score in visited:
                continue

            cost += 1

            # update scores:
            new_g_score = g_score + 1
            new_f_score = new_g_score + calculate_heuristic(next_state)

            # Add new state to openset
            heappush(open_set, (new_f_score, new_g_score, next_state.tobytes(), path + [act]))

    return None, float('inf')  # No solution found


# Main

In [76]:
test_goal = np.arange(1, PUZZLE_DIM*PUZZLE_DIM, 1)
test_goal = np.append(test_goal, 0)
test_goal = test_goal.reshape((PUZZLE_DIM, PUZZLE_DIM))

# Try the upgrade depth search

In [77]:
#depth_limited_search(state, test_goal)

# Try the A* algorithm

In [78]:
actions, costValue = enhanced_a_star(state, test_goal)

In [79]:
qualily(actions)

128

In [80]:
actions

[Action(pos1=(1, 1), pos2=(1, 0)),
 Action(pos1=(1, 0), pos2=(2, 0)),
 Action(pos1=(2, 0), pos2=(2, 1)),
 Action(pos1=(2, 1), pos2=(2, 2)),
 Action(pos1=(2, 2), pos2=(1, 2)),
 Action(pos1=(1, 2), pos2=(0, 2)),
 Action(pos1=(0, 2), pos2=(0, 3)),
 Action(pos1=(0, 3), pos2=(1, 3)),
 Action(pos1=(1, 3), pos2=(1, 4)),
 Action(pos1=(1, 4), pos2=(2, 4)),
 Action(pos1=(2, 4), pos2=(2, 3)),
 Action(pos1=(2, 3), pos2=(1, 3)),
 Action(pos1=(1, 3), pos2=(1, 4)),
 Action(pos1=(1, 4), pos2=(0, 4)),
 Action(pos1=(0, 4), pos2=(0, 3)),
 Action(pos1=(0, 3), pos2=(1, 3)),
 Action(pos1=(1, 3), pos2=(1, 2)),
 Action(pos1=(1, 2), pos2=(1, 1)),
 Action(pos1=(1, 1), pos2=(0, 1)),
 Action(pos1=(0, 1), pos2=(0, 2)),
 Action(pos1=(0, 2), pos2=(1, 2)),
 Action(pos1=(1, 2), pos2=(1, 1)),
 Action(pos1=(1, 1), pos2=(1, 0)),
 Action(pos1=(1, 0), pos2=(0, 0)),
 Action(pos1=(0, 0), pos2=(0, 1)),
 Action(pos1=(0, 1), pos2=(1, 1)),
 Action(pos1=(1, 1), pos2=(1, 0)),
 Action(pos1=(1, 0), pos2=(2, 0)),
 Action(pos1=(2, 0),

In [81]:
state

array([[14,  8,  9,  1, 18],
       [22,  0, 15,  5, 17],
       [ 2, 11, 21, 16,  4],
       [19, 12, 13,  6, 24],
       [20,  3,  7, 23, 10]])

In [82]:
test_goal

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24,  0]])